name: hex_edit
description: macOS 风格十六进制编辑器
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # macOS UI 组件库
  macos_ui: ^2.0.0
  
  # 窗口管理
  window_manager: ^0.3.7
  
  # 文件选择
  file_picker: ^6.1.1
  
  # 字符编码
  charset: ^1.3.0
  
  # 状态管理
  provider: ^6.1.1
  
  # 用户偏好设置
  shared_preferences: ^2.2.2
  
  # 系统路径
  path_provider: ^2.1.1
  
  # 路径处理
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # 如果需要添加资源文件
  # assets:
  #   - assets/images/
  #   - assets/icons/
